name: common

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  dio: ^5.4.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1 
  formz: ^0.4.1
  go_router: ^13.2.0
  get_storage: ^2.1.1
  intl: ^0.18.1
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.4
  http_parser: ^4.0.2
  mime_type: ^1.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  flutter_cache_manager: ^3.3.1
  flutter_secure_storage: ^9.0.0
  lottie: ^3.1.0
  uuid: ^4.4.0
  firebase_messaging: ^15.2.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0
  mocktail: ^1.0.2

flutter:
  uses-material-design: true